name: Deploy Pages
on:
  workflow_dispatch:
  push:
    branches: [master]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'


      - name: Clean install (remove lockfile and node_modules)
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build all lessons
        run: |
          # Create dist directory
          mkdir -p dist
          
          # Find all slides.md files and build them
          find lessons -name "slides.md" | sort | while read slidepath; do
            # Extract directory path (remove /slides.md suffix)
            dirpath=$(dirname "$slidepath")
            
            # Create output directory path
            outdir="dist/$dirpath"
            
            # Determine the base URL path
            basepath="/${{github.event.repository.name}}/$dirpath/"
            
            echo "Building $slidepath to $outdir with base $basepath"
            npx slidev build --base "$basepath" "$slidepath" --out "$outdir"
          done

      - name: Generate index.html
        run: |
          cat > dist/index.html << 'EOF'
          <html>
            <header>
              <link rel="stylesheet" href="css/pico.fluid.classless.min.css">
            </header>
            <body>
              <h1>Columbia BigD103 - Course Lessons</h1>
              <ul>
          EOF

          # Find all slides.md files and generate links
          find lessons -name "slides.md" | sort | while read slidepath; do
            # Extract directory path (remove lessons/ prefix and /slides.md suffix)
            dirpath=$(dirname "$slidepath")

            # Convert directory path to title (replace slashes and underscores with spaces, capitalize)
            title=$(echo "$dirpath" | sed 's|/| - |g' | sed 's|_| |g' | sed 's|\b\w|\U&|g')

            echo "<li><a href=\"./$dirpath/\">$title</a></li>" >> dist/index.html
          done

          cat >> dist/index.html << 'EOF'
              </ul>
            </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
